org: mcdaviddj
app: zoey-bot
service: zoey-bot

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  notification:
    handler: handler.notification
    events:
      - httpApi:
          method: GET
          path: /notification
  
  eventsub_callback:
    handler: handler.eventsub_callback
    events:
      - httpApi:
          method: POST
          path: /eventsub/callback

plugins:
  - serverless-offline